set(
    ROGII_RAPIDJSON_VERSION_MAJOR
    1
)

set(
    ROGII_RAPIDJSON_VERSION_MINOR
    1
)

set(
    ROGII_RAPIDJSON_VERSION_PATCH
    0
)

set(
    ROGII_RAPIDJSON_VERSION
    "${ROGII_RAPIDJSON_VERSION_MAJOR}.${ROGII_RAPIDJSON_VERSION_MINOR}.${ROGII_RAPIDJSON_VERSION_PATCH}"
)
